"""Slack digest formatter."""

from __future__ import annotations

from typing import Sequence

from featrank.schemas import PrioritizedCluster


class SlackFormatter:
    """Format top clusters as a Slack-ready plain-text digest."""

    def __init__(self, top_n: int = 10) -> None:
        self.top_n = top_n

    def format(self, clusters: Sequence[PrioritizedCluster]) -> str:
        top = list(clusters)[: self.top_n]
        lines: list[str] = [
            ":bar_chart: *featrank Weekly Priority Digest*",
            f"Top {len(top)} feature clusters ranked by business value",
            "",
        ]

        for c in top:
            medal = {1: ":first_place_medal:", 2: ":second_place_medal:", 3: ":third_place_medal:"}.get(
                c.priority_rank, f"*#{c.priority_rank}*"
            )
            lines.append(
                f"{medal} *{c.label}* — score: {c.priority_score:.1f}  "
                f"| {c.request_count} requests | {c.unique_users} users | ${c.total_mrr:,.0f} MRR"
            )
            if c.llm_diagnosis:
                lines.append(f"   > {c.llm_diagnosis}")
            lines.append("")

        lines.append("_Generated by featrank — https://github.com/askmy-stack/featrank_")
        return "\n".join(lines)
